# Generated by Django 2.1.5 on 2019-01-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas_Ana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('descrição', models.CharField(max_length=200)),
                ('vencimento', models.DateField()),
                ('quitado', models.CharField(max_length=20)),
            ],
        ),
    ]
