# Generated by Django 2.1.5 on 2019-02-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Despesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas_ana',
            name='Forma_Pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Cartão Crediário', 'Cartão Crediário'), ('Cheque', 'Cheque')], default='Dinheiro', max_length=200),
        ),
        migrations.AddField(
            model_name='despesas_ana',
            name='Tipo_Despesa',
            field=models.CharField(choices=[('Remédio', 'Remédio'), ('Roupas', 'Roupas'), ('Alimentação', 'Alimentação'), ('educação', 'educação'), ('Transporte', 'Transporte'), ('Outros', 'Outros')], default='Remedío', max_length=200),
        ),
        migrations.AlterField(
            model_name='despesas_ana',
            name='descrição',
            field=models.CharField(max_length=89),
        ),
        migrations.AlterField(
            model_name='despesas_ana',
            name='quitado',
            field=models.CharField(max_length=50),
        ),
    ]
